apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-self-provisioner-disable
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: AC Access Control
    policy.open-cluster-management.io/controls: AC-6 Least Privilege
    policy.open-cluster-management.io/description: Restricts and disables the default self-provisioner ClusterRoleBinding to prevent ordinary users from creating new projects or namespaces without administrative approval. By enforcing mustonlyhave with empty subjects, this policy ensures that no user or group is bound to the self-provisioner role. This reduces the risk of uncontrolled namespace sprawl and enforces least privilege
spec:
  remediationAction: inform
  disabled: true
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: self-provisioner-disable
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: self-provisioners
                  annotations:
                    rbac.authorization.kubernetes.io/autoupdate: 'false'
                subjects: []
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: self-provisioner
