apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-fips-compliance
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/description: Ensures FIPS mode is enabled cluster-wide by applying MachineConfigs that enforce FIPS on both worker and master nodes. This supports NIST Cybersecurity Framework (NIST-CSF) baseline configuration requirements (PR.IP-1).
spec:
  remediationAction: inform
  disabled: true
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-fips-compliance
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  labels:
                    machineconfiguration.openshift.io/role: worker
                  name: 99-worker-fips
                spec:
                  fips: true
            - complianceType: musthave
              objectDefinition:
                apiVersion: machineconfiguration.openshift.io/v1
                kind: MachineConfig
                metadata:
                  labels:
                    machineconfiguration.openshift.io/role: master
                  name: 99-master-fips
                spec:
                  fips: true
