apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-cluster-operator-check
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
    policy.open-cluster-management.io/description: Monitors the health of all OpenShift cluster operators to ensure they remain available and not in a degraded state. This policy checks the status conditions of ClusterOperator resources and reports noncompliance if any operator is unavailable (Available=False) or degraded (Degraded=True).
spec:
  remediationAction: inform
  disabled: true
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-operator-available
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                status:
                  conditions:
                    - status: 'False'
                      type: Available
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-operator-degraded
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: ClusterOperator
                status:
                  conditions:
                    - status: 'True'
                      type: Degraded
