apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-no-previleged-pods
  namespace: policies
  annotations:
    policy.open-cluster-management.io/categories: SC System and Communications Protection
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/controls: SC-4 Information In Shared Resources
    policy.open-cluster-management.io/description: Prevents the creation of privileged pods in the cluster by enforcing a custom Security Context Constraint (SCC) that disables privileged containers and privilege escalation. This policy ensures workloads run with the least privileges required, protecting sensitive resources and reducing attack surfaces.
spec:
  remediationAction: inform
  disabled: true
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: scc-no-privileged-pods
        spec:
          remediationAction: inform
          severity: high
          namespaceSelector:
            exclude: ["kube-*", "openshift-*"]
            include: ["*"]
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: security.openshift.io/v1
                kind: SecurityContextConstraints
                metadata:
                  name: no-privileged-container-scc
                priority: 10 # make this scc win over privileged scc
                allowPrivilegedContainer: false
                allowPrivilegeEscalation: false
