apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-comp-operator
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CA Security Assessment and Authorization
    policy.open-cluster-management.io/controls: CA-2 Security Assessments, CA-7 Continuous Monitoring
    policy.open-cluster-management.io/description: Deploys and ensures the presence of the OpenShift Compliance Operator. This policy validates that the openshift-compliance namespace, operator group, catalog source, and subscription for the Compliance Operator are properly configured. The Compliance Operator provides automated compliance scans and continuous monitoring against security benchmarks
spec:
  remediationAction: inform
  disabled: true
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-ns
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-compliance
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-catalog-source
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: CatalogSource
                metadata:
                  name: compliance-operator
                  namespace: openshift-marketplace
                spec:
                  # TODO: check different between these two line
                  # displayName: Compliance Operator Upstream
                  # publisher: github.com/openshift/compliance-operator
                  # sourceType: grpc
                  # image: quay.io/compliance-operator/compliance-operator-index:latest
                  displayName: Compliance Operator
                  publisher: github.com/ComplianceAsCode/compliance-operator
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-group
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: compliance-operator
                  namespace: openshift-compliance
                spec:
                  targetNamespaces:
                    - openshift-compliance
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: comp-operator-subscription
        spec:
          remediationAction: inform # will be overridden by remediationAction in parent policy
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: compliance-operator-sub
                  namespace: openshift-compliance
                spec:
                  # channel: alpha
                  channel: stable
                  name: compliance-operator
                  source: compliance-operator
                  sourceNamespace: openshift-marketplace
