apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-placement-global
  namespace: policies
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            vendor: OpenShift
