apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: policy-placement-openshift
  namespace: policies
spec:
  clusterSets:
    - global
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            vendor: OpenShift
            feature.open-cluster-management.io/addon-governance-policy-framework: available
            feature.open-cluster-management.io/addon-config-policy-controller: available
